// File: src/config.ts
// [VERIFIED on M1 2026-06-18] model sources/sizes from RECONCILE.md + Phase-0 spikes.
// Built-in model constants are referenced by TOKEN name here; the sdk.ts shim resolves
// each token to the real exported @qvac/sdk value (a ModelDescriptor object or string).
import process from "node:process";
import { existsSync } from "node:fs";

export type ResidentMode = "resident" | "hybrid" | "sequential" | "fallback";

export interface ModelSpec {
  /** Human label used in perf logs and UI. Translation roles are per-direction (e.g. "translation:fr>en"). */
  role: "stt" | "medpsy" | "embeddings" | "tts" | `translation:${string}`;
  /** SDK built-in constant TOKEN (resolved in sdk.ts), HF GGUF URL, or local path. */
  modelSrc: string;
  /** QVAC modelType discriminator. */
  modelType: "whisper" | "llm" | "embeddings" | "tts" | "nmtcpp-translation";
  /** Context window (llm/embeddings only). */
  ctxSize?: number;
  /** Engine-specific load config. REQUIRED for tts (e.g. {ttsEngine:"supertonic",language:"en"}). */
  modelConfig?: Record<string, unknown>;
}

/** Supertonic TTS output is 44.1 kHz mono int16 PCM (verified live, RECONCILE.md Phase-3). */
export const TTS_SAMPLE_RATE = 44100;

/** MedPsy default = 1.7B Q4_K_M (1.28 GB, cached at .models/). 4B is opt-in high-accuracy mode. */
const MEDPSY_1_7B_LOCAL = new URL("../.models/medpsy-1.7b-q4_k_m-imat.gguf", import.meta.url).pathname;
// Cold-clone fallback (C-3): .models/ + *.gguf are gitignored, so a fresh clone lacks the local file and a
// bare local path does NOT auto-download. Fall back to the HF GGUF URL (a URL auto-downloads + caches, the
// way MODEL_ID=4b already does), so `npm start` works OOTB for a judge. The local file is still preferred
// when present (offline, no download). Filename + repo match remote-api-manifest.json / README.
const MEDPSY_1_7B_URL =
  "https://huggingface.co/qvac/MedPsy-1.7B-GGUF/resolve/main/medpsy-1.7b-q4_k_m-imat.gguf";
const MEDPSY_4B =
  "https://huggingface.co/qvac/MedPsy-4B-GGUF/resolve/main/medpsy-4b-q4_k_m-imat.gguf";

export const config = {
  port: Number(process.env.PORT ?? 3010),
  /** "1.7b" (default) or "4b" — selects the MedPsy variant. */
  modelId: (process.env.MODEL_ID ?? "1.7b").toLowerCase(),
  /** Optional — only used to authorize/speed the first-run model asset download. */
  hfToken: process.env.HF_TOKEN ?? undefined,
  /** Native @qvac/rag workspace name (persists at ~/.qvac/rag-hyperdb). */
  ragWorkspace: process.env.TRIAGE0_RAG_WORKSPACE ?? "triage0-who-protocols",
  /** Citation sidecar map (id -> {protocol,title,page,section}); regenerated by ingest.
   *  TRIAGE0_CITATION_MAP overrides the path (used by tests to avoid touching the real sidecar). */
  citationMapPath: process.env.TRIAGE0_CITATION_MAP ?? new URL("../data/rag/citation-map.json", import.meta.url).pathname,
  /**
   * ragSearch similarity floor; below this -> abstain (UNKNOWN card, no invented citation).
   * Re-calibrated 2026-06-21 (scripts/probe-retrieval.ts): in-domain mental-health cases bottom out
   * at ~0.697 (psychosis in lay language), off-domain negatives (cake 0.673, car 0.654, taxes/flights
   * lower) top out ~0.673 — a narrow but real gap. 0.685 sits in it: psychosis grounds, off-domain
   * abstains. The model's UNKNOWN enum is the second-line backstop for anything that slips through.
   */
  ragScoreThreshold: Number(process.env.RAG_THRESHOLD ?? 0.685),
  /** Resident strategy. Phase-0 spike proved unload reclaims fully -> "resident" is safe. */
  residentMode: (process.env.RESIDENT_MODE as ResidentMode) ?? "resident",
};

export function medpsySpec(): ModelSpec {
  // 4b → URL (auto-download). 1.7b → local cache if present, else the HF URL (auto-download on cold clone).
  const src =
    config.modelId === "4b" ? MEDPSY_4B : existsSync(MEDPSY_1_7B_LOCAL) ? MEDPSY_1_7B_LOCAL : MEDPSY_1_7B_URL;
  // ctx 3072 (was 4096): measured peak is ~1230 prompt + ≤1024 reason ≈ 2250 tokens, so 3072 keeps a
  // comfortable margin while trimming KV-cache RAM + load time on the 8GB target. (cache-type-k/v and
  // flash_attn are NOT exposed by @qvac/sdk@0.13.3 — verified absent from the SDK dist — so ctx is the
  // only supported KV lever here.)
  return { role: "medpsy", modelSrc: src, modelType: "llm", ctxSize: 3072 };
}

/** TTS voices supported end-to-end (STT/translation already cover fr+es). Supertonic2 is multilingual. */
export const TTS_LANGS = ["en", "fr", "es"] as const;
export type TtsLang = (typeof TTS_LANGS)[number];

/**
 * Voice model per language. The multilingual Supertonic2 GGUF speaks en/fr/es, but the `language` is a
 * LOAD-TIME engine option (the per-call TTSRunInput has no language field), so each language is its own
 * load. The orchestrator keeps ONE voice resident and swaps it when the language changes — cheap on the
 * 8GB target because the spoken guidance is synthesized in the BACKGROUND, so a voice reload is hidden.
 */
export function ttsSpec(lang: TtsLang): ModelSpec {
  return {
    role: "tts",
    modelSrc: "TTS_MULTILINGUAL_SUPERTONIC2_Q8_0",
    modelType: "tts",
    modelConfig: { ttsEngine: "supertonic", language: lang },
  };
}

export const registry = {
  // Built-in SDK descriptor tokens — confirmed exported by @qvac/sdk@0.13.3 (RECONCILE.md).
  // STT: multilingual SMALL (was tiny.en — English-only + least accurate). Small transcribes en/fr/es and
  // is far more accurate on real speech. `detect_language:true` auto-detects the spoken language and
  // `translate:false` keeps the transcript in THAT language (the default translate-to-English would turn a
  // French case into English text, which would then skip the multilingual pipeline). So French speech →
  // French text in the box → the triage flow detects FR and translates as designed.
  // `language:"auto"` makes whisper.cpp auto-detect the spoken language AND transcribe in it; `translate:false`
  // keeps the transcript in that language (the default would translate a French case to English text, which
  // then skips the multilingual pipeline). NB: `detect_language` is a DETECT-ONLY mode (returns the language
  // without transcribing) — the wrong flag here; language:"auto" is what enables auto-detect + transcription.
  stt: { role: "stt", modelSrc: "WHISPER_SMALL_Q8_0", modelType: "whisper", modelConfig: { language: "auto", translate: false } } as ModelSpec,
  // Default voice = English; ttsSpec(lang) swaps in fr/es on demand (see orchestrator.withTts).
  tts: ttsSpec("en"),
  embeddings: {
    role: "embeddings",
    modelSrc: process.env.EMBED_SRC ?? "GTE_LARGE_FP16",
    modelType: "embeddings",
  } as ModelSpec,
  medpsy: medpsySpec(),
};

/** Phase 4 multilingual: the case is translated to English BEFORE routing and the card/plan back to the
 *  source language AFTER. Bergamot NMT runs through the SDK bridge (modelType "nmtcpp-translation"); the
 *  direct @qvac/translation-nmtcpp class is Bare-runtime-only and fails under Node. Model sources are the
 *  SDK's built-in registry tokens (resolved in sdk.ts), fetched + cached to ~/.qvac on first load. Generation
 *  params mirror the SDK's Bergamot example; temperature 0 + beamsize 1 = deterministic (greedy). */
const bergamotSpec = (from: string, to: string, token: string): ModelSpec => ({
  role: `translation:${from}>${to}`,
  modelSrc: token,
  modelType: "nmtcpp-translation",
  modelConfig: { engine: "Bergamot", from, to, beamsize: 1, normalize: 1, temperature: 0, norepeatngramsize: 3, lengthpenalty: 1.2 },
});

/** Target languages = French + Spanish (FINAL-POSITION 1C). 4 directions: in (→en) + out (en→). */
export const TRANSLATION_LANGS = ["fr", "es"] as const;
export type TranslationLang = (typeof TRANSLATION_LANGS)[number];

export const translations: Record<string, ModelSpec> = {
  "fr>en": bergamotSpec("fr", "en", "BERGAMOT_FR_EN"),
  "en>fr": bergamotSpec("en", "fr", "BERGAMOT_EN_FR"),
  "es>en": bergamotSpec("es", "en", "BERGAMOT_ES_EN"),
  "en>es": bergamotSpec("en", "es", "BERGAMOT_EN_ES"),
};
