// File: src/config.ts
// [VERIFIED on M1 2026-06-18] model sources/sizes from RECONCILE.md + Phase-0 spikes.
// Built-in model constants are referenced by TOKEN name here; the sdk.ts shim resolves
// each token to the real exported @qvac/sdk value (a ModelDescriptor object or string).
import process from "node:process";

export type ResidentMode = "resident" | "hybrid" | "sequential" | "fallback";

export interface ModelSpec {
  /** Human label used in perf logs and UI. */
  role: "stt" | "medpsy" | "embeddings" | "tts";
  /** SDK built-in constant TOKEN (resolved in sdk.ts), HF GGUF URL, or local path. */
  modelSrc: string;
  /** QVAC modelType discriminator. */
  modelType: "whisper" | "llm" | "embeddings" | "tts";
  /** Context window (llm/embeddings only). */
  ctxSize?: number;
  /** Engine-specific load config. REQUIRED for tts (e.g. {ttsEngine:"supertonic",language:"en"}). */
  modelConfig?: Record<string, unknown>;
}

/** Supertonic TTS output is 44.1 kHz mono int16 PCM (verified live, RECONCILE.md Phase-3). */
export const TTS_SAMPLE_RATE = 44100;

/** MedPsy default = 1.7B Q4_K_M (1.28 GB, cached at .models/). 4B is opt-in high-accuracy mode. */
const MEDPSY_1_7B_LOCAL = new URL("../.models/medpsy-1.7b-q4_k_m-imat.gguf", import.meta.url).pathname;
const MEDPSY_4B =
  "https://huggingface.co/qvac/MedPsy-4B-GGUF/resolve/main/medpsy-4b-q4_k_m-imat.gguf";

export const config = {
  port: Number(process.env.PORT ?? 3010),
  /** "1.7b" (default) or "4b" — selects the MedPsy variant. */
  modelId: (process.env.MODEL_ID ?? "1.7b").toLowerCase(),
  /** Optional — only used to authorize/speed the first-run model asset download. */
  hfToken: process.env.HF_TOKEN ?? undefined,
  /** Native @qvac/rag workspace name (persists at ~/.qvac/rag-hyperdb). */
  ragWorkspace: process.env.TRIAGE0_RAG_WORKSPACE ?? "triage0-who-protocols",
  /** Citation sidecar map (id -> {protocol,title,page,section}); regenerated by ingest.
   *  TRIAGE0_CITATION_MAP overrides the path (used by tests to avoid touching the real sidecar). */
  citationMapPath: process.env.TRIAGE0_CITATION_MAP ?? new URL("../data/rag/citation-map.json", import.meta.url).pathname,
  /**
   * ragSearch similarity floor; below this -> abstain (UNKNOWN card, no invented citation).
   * Calibrated 2026-06-19 on GTE_LARGE_FP16: correct hits score >=0.74, off-domain negatives
   * (taxes/car repair/cake) top out ~0.66 — GTE has a high similarity floor, so 0.30 gated
   * nothing. 0.70 cleanly separates the two on this corpus.
   */
  ragScoreThreshold: Number(process.env.RAG_THRESHOLD ?? 0.70),
  /** Resident strategy. Phase-0 spike proved unload reclaims fully -> "resident" is safe. */
  residentMode: (process.env.RESIDENT_MODE as ResidentMode) ?? "resident",
};

export function medpsySpec(): ModelSpec {
  const src = config.modelId === "4b" ? MEDPSY_4B : MEDPSY_1_7B_LOCAL;
  // ctx 3072 (was 4096): measured peak is ~1230 prompt + ≤1024 reason ≈ 2250 tokens, so 3072 keeps a
  // comfortable margin while trimming KV-cache RAM + load time on the 8GB target. (cache-type-k/v and
  // flash_attn are NOT exposed by @qvac/sdk@0.13.3 — verified absent from the SDK dist — so ctx is the
  // only supported KV lever here.)
  return { role: "medpsy", modelSrc: src, modelType: "llm", ctxSize: 3072 };
}

export const registry = {
  // Built-in SDK descriptor tokens — confirmed exported by @qvac/sdk@0.13.3 (RECONCILE.md).
  stt: { role: "stt", modelSrc: "WHISPER_EN_TINY_Q8_0", modelType: "whisper" } as ModelSpec,
  // TTS load REQUIRES modelConfig (the load-model union's tts branch is non-optional) — RECONCILE.md Phase-3.
  tts: { role: "tts", modelSrc: "TTS_EN_SUPERTONIC_Q8_0", modelType: "tts", modelConfig: { ttsEngine: "supertonic", language: "en" } } as ModelSpec,
  embeddings: {
    role: "embeddings",
    modelSrc: process.env.EMBED_SRC ?? "GTE_LARGE_FP16",
    modelType: "embeddings",
  } as ModelSpec,
  medpsy: medpsySpec(),
};
