// File: src/rag/store.ts
// RAG store over the NATIVE @qvac/rag HyperDB engine (workspace persists at ~/.qvac/rag-hyperdb).
// ragSearch returns only {id, content, score}, so citation metadata (protocol/title/page/section)
// is carried by a deterministic chunk id + a JSON sidecar map. Reconciled + proven: spike3-rag.ts.
import { performance } from "node:perf_hooks";
import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { config } from "../config.js";
import {
  RagEmbeddedDoc,
  RagSaveResult,
  ragDeleteWorkspace,
  ragListWorkspaces,
  ragSaveEmbeddings,
  ragSearch,
} from "../qvac/sdk.js";
import { embedBatchTimed } from "../qvac/engine.js";
import { logPerf } from "../qvac/perf-logger.js";

export interface Citation {
  protocol: string; // "IMCI" | "mhGAP"
  title: string; // human document title used in every citation
  page: number;
  section: string; // short excerpt used as the in-card citation anchor
}

export interface StoredChunk extends Citation {
  id: string;
  content: string;
}

/** A chunk ready to embed + store. */
export interface IngestChunk extends Citation {
  id: string;
  content: string;
}

export interface SearchHit {
  id: string;
  text: string;
  source_ref: string; // "WHO IMCI Chart Booklet, p.23 — \"Fast breathing…\""
  protocol: string;
  citation: Citation;
  score: number; // semantic: cosine 0..1 (compare to ragScoreThreshold). keyword: term-coverage 0..1 (do NOT compare to it).
  mode: "semantic" | "keyword";
}

type CitationMap = Record<string, StoredChunk>;

// ── citation sidecar (id -> citation), regenerated by ingest ─────────────────────

let _map: CitationMap | null = null;
let _mapMtime = -1;

function mapPath(): string {
  return config.citationMapPath;
}

/**
 * mtime-keyed cache. D2 fix: never cache an empty map *permanently* when the sidecar is missing —
 * a server that queried before `npm run ingest` finished would otherwise serve degraded citations
 * forever. We re-check the file on every call and reload when it appears or changes.
 */
export function loadCitationMap(): CitationMap {
  const p = mapPath();
  if (!existsSync(p)) return _map ?? (_map = {}); // transient empty; _mapMtime stays stale → reloads when file appears
  const mtime = statSync(p).mtimeMs;
  if (_map && mtime === _mapMtime) return _map;
  try {
    _map = JSON.parse(readFileSync(p, "utf8")) as CitationMap;
    _mapMtime = mtime;
  } catch {
    _map ??= {};
  }
  return _map;
}

function saveCitationMap(map: CitationMap): void {
  const p = mapPath();
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, JSON.stringify(map, null, 2), "utf8");
  _map = map;
  _mapMtime = statSync(p).mtimeMs;
}

export function chunkCount(): number {
  return Object.keys(loadCitationMap()).length;
}

function sourceRef(c: Citation): string {
  return `${c.title}, p.${c.page} — "${c.section}…"`;
}

/**
 * Fallback citation when the sidecar is missing an entry (should never happen in normal flow —
 * it signals a sidecar/store mismatch). D3 fix: make it VISIBLY degraded and warn, rather than
 * fabricating a plausible-looking citation that hides the inconsistency.
 */
export function citationFromId(id: string): Citation {
  const [protocol = "WHO", pageTok = "p0"] = id.split("|");
  const page = Number(pageTok.replace(/\D/g, "")) || 0;
  console.warn(`[store] citation sidecar miss for chunk "${id}" — store/sidecar mismatch; emitting degraded citation`);
  return { protocol, title: `${protocol} (citation metadata unavailable)`, page, section: "" };
}

// ── workspace lifecycle ──────────────────────────────────────────────────────────

/** Idempotent ingest support: drop the workspace + sidecar so a re-ingest starts clean. */
export async function resetWorkspace(): Promise<void> {
  await ragDeleteWorkspace(config.ragWorkspace);
  saveCitationMap({});
}

export async function workspaceExists(): Promise<boolean> {
  const list = await ragListWorkspaces();
  return list.some((w) => w.name === config.ragWorkspace);
}

// ── pure save-path validators (D1/C1 — unit-tested) ──────────────────────────────

/** D1: refuse to save on vector/chunk desync or a degenerate (empty/NaN) embedding. Throws. */
export function assertVectorsAligned(chunkIds: string[], vectors: number[][]): void {
  if (vectors.length !== chunkIds.length) {
    throw new Error(
      `embed returned ${vectors.length} vectors for ${chunkIds.length} chunks — index desync, refusing to save`,
    );
  }
  const badIdx = vectors.findIndex((v) => !v?.length || v.some((x) => !Number.isFinite(x)));
  if (badIdx >= 0) throw new Error(`chunk ${chunkIds[badIdx]} embedded to an invalid vector — refusing to save`);
}

/** C1: split SDK save results into the ids the store confirmed vs the rejections. */
export function partitionSaveResults(results: RagSaveResult[]): {
  fulfilledIds: Set<string>;
  rejected: RagSaveResult[];
} {
  return {
    fulfilledIds: new Set(results.filter((r) => r.status === "fulfilled" && r.id).map((r) => r.id!)),
    rejected: results.filter((r) => r.status === "rejected"),
  };
}

// ── write path (used by ingest) ────────────────────────────────────────────────

/**
 * Embed a batch of chunks and persist them to the native store + sidecar.
 * One embed perf row per call (batched). Returns the number saved.
 */
export async function saveChunks(embedModelId: string, chunks: IngestChunk[]): Promise<number> {
  // Defensive: never send an empty/whitespace-only string to the embedder.
  chunks = chunks.filter((c) => c.content.trim().length > 0);
  if (chunks.length === 0) return 0;
  const { vectors } = await embedBatchTimed({
    modelId: embedModelId,
    texts: chunks.map((c) => c.content),
    phase: "ingest",
  });

  // D1: refuse to save on any vector/chunk desync or a degenerate (empty/NaN) embedding —
  // either would silently pair the wrong clinical text with the wrong citation id.
  assertVectorsAligned(chunks.map((c) => c.id), vectors);

  const docs: RagEmbeddedDoc[] = chunks.map((c, i) => ({
    id: c.id,
    content: c.content,
    embedding: vectors[i],
    embeddingModelId: embedModelId,
    metadata: { protocol: c.protocol, title: c.title, page: c.page, section: c.section },
  }));
  const results = await ragSaveEmbeddings({ workspace: config.ragWorkspace, documents: docs });

  // C1: never let the sidecar claim a chunk the store rejected. Fail loud on any rejection,
  // and only record ids the store confirmed it persisted.
  const { fulfilledIds, rejected } = partitionSaveResults(results);
  if (rejected.length) {
    throw new Error(
      `ragSaveEmbeddings rejected ${rejected.length}/${results.length}: ` +
        rejected.slice(0, 3).map((r) => r.error ?? r.id ?? "?").join("; "),
    );
  }
  // If the SDK reported fulfilled ids, persist exactly those; otherwise (no per-doc report) all.
  const persisted = fulfilledIds.size ? chunks.filter((c) => fulfilledIds.has(c.id)) : chunks;

  const map = loadCitationMap();
  for (const c of persisted) {
    map[c.id] = { id: c.id, content: c.content, protocol: c.protocol, title: c.title, page: c.page, section: c.section };
  }
  saveCitationMap(map);
  return persisted.length;
}

// ── read path (used by triage) ───────────────────────────────────────────────────

/**
 * Top-k semantic retrieval via native ragSearch (query embedded internally with embedModelId).
 * Resolves each hit's citation from the sidecar. Logs one "search" perf row.
 */
export async function search(args: {
  embedModelId: string;
  queryText: string;
  k?: number;
  phase?: string;
}): Promise<SearchHit[]> {
  const k = args.k ?? 4;
  const map = loadCitationMap();
  const t0 = performance.now();
  const hits = await ragSearch({
    modelId: args.embedModelId,
    query: args.queryText,
    topK: k,
    workspace: config.ragWorkspace,
  });
  const ms = performance.now() - t0;
  logPerf({
    ts: new Date().toISOString(),
    phase: args.phase ?? "triage", event: "search", modelId: args.embedModelId,
    promptTokens: Math.ceil(args.queryText.length / 4), durationMs: Math.round(ms),
  });

  return hits.map((h) => {
    const stored = map[h.id];
    const citation: Citation = stored
      ? { protocol: stored.protocol, title: stored.title, page: stored.page, section: stored.section }
      : citationFromId(h.id);
    return {
      id: h.id,
      text: h.content,
      source_ref: sourceRef(citation),
      protocol: citation.protocol,
      citation,
      score: h.score,
      mode: "semantic" as const,
    };
  });
}

/**
 * Keyword fallback over the sidecar contents — degraded mode when embeddings are unavailable.
 * D5: `score` here is TERM-COVERAGE (0..1), a DIFFERENT scale from semantic cosine — callers must
 * branch on `mode` and must NOT compare a keyword score to `config.ragScoreThreshold`.
 */
export function keywordSearch(queryText: string, k = 4): SearchHit[] {
  const terms = queryText.toLowerCase().split(/\W+/).filter((t) => t.length > 3);
  const map = loadCitationMap();
  const scored: SearchHit[] = Object.values(map).map((c) => {
    const lc = c.content.toLowerCase();
    const hits = terms.reduce((n, t) => n + (lc.includes(t) ? 1 : 0), 0);
    const citation: Citation = { protocol: c.protocol, title: c.title, page: c.page, section: c.section };
    return {
      id: c.id,
      text: c.content,
      source_ref: sourceRef(citation),
      protocol: c.protocol,
      citation,
      score: terms.length ? hits / terms.length : 0,
      mode: "keyword" as const,
    };
  });
  scored.sort((a, b) => b.score - a.score);
  return scored.slice(0, k);
}
